---
repos:
    -   repo: https://github.com/pre-commit/pre-commit-hooks
        rev: v4.3.0
        hooks:
        -   id: check-merge-conflict
        -   id: debug-statements
        -   id: end-of-file-fixer
        -   id: mixed-line-ending
        -   id: trailing-whitespace
        -   id: check-yaml
        -   id: sort-simple-yaml
    - repo: https://github.com/markdownlint/markdownlint
      rev: v0.11.0
      hooks:
        -   id: markdownlint
            args:
              ["-t MD013"]
    - repo: https://github.com/psf/black
      rev: 22.6.0
      hooks:
          - id: black
    - repo: https://github.com/pycqa/isort
      rev: 5.10.1
      hooks:
      - id: isort
        args: ["--profile", "black", "--filter-files"]
    - repo: https://github.com/pycqa/pydocstyle
      rev: 6.1.1
      hooks:
      -   id: pydocstyle
    - repo: https://github.com/pre-commit/mirrors-mypy
      rev: v0.971
      hooks:
      -   id: mypy
    - repo: local
      hooks:
          # Note: pylint to be run locally:
          # https://pylint.pycqa.org/en/latest/user_guide/pre-commit-integration.html
          - id: pylint
            name: pylint
            entry: pylint
            language: system
            types: [python]
            args:
              [
                --rcfile=linters/.pylintrc
              ]
          # Note: istyle to be run locally (must be executable by shell):
          # https://github.com/thomasrussellmurphy/istyle-verilog-formatter
          # The binary must reside in the linters directory
          - id: iStyle
            name: iStyle
            entry: linters/istyle
            language: system
            types: [verilog]
            args:
              [
                --style=gnu
              ]
          # A note about other linters:
          # verilator (https://www.veripool.org/verilator/) seems to be a much
          # used option, however for the current project it emits noise around
          # delay statements (unsupported) and around the
          # "Signal unoptimizable" (https://verilator.org/warn/UNOPTFLAT?v=4.224)
          # bug
          # (see https://github.com/verilator/verilator/issues/63)
          # Verible also seems like a nice linter, but does not support MacOs at the present
          # https://github.com/chipsalliance/verible
